### PR TITLE
Show locale switcher when using multilocale editor

### PR DESCRIPTION
**Pull request by vojtasvoboda**
When using RainLab.Tranlate and multilocale editor, we should show locale switcher.

snimek obrazovky 2016-09-12 v 10 09 14

Please make also October market update.

### CODE REVIEW

**Comment by gergo85** [comment]
+1

**Comment by vojtasvoboda** [comment]
🆙

**Comment by vojtasvoboda** [comment]
🙏

**Comment by vojtasvoboda** [comment]
🆙

**Comment by a-salihov** [comment]
Is this patch workable? I see it in my source files but I don't see Locale switcher when CKeditor or TinyMCE are selected. 
Locale switcher is displayed only for default Markdown editor.
oc-wysiwyg-editors 1.2.8, Translate plugin 1.2.11, Blog plugin 1.2.16

**Comment by vojtasvoboda** [comment]
@a-salihov yes you are right, this patch is only for OctoberCMS wysiwyg editor Froala. Not for TinyMCE nor CKEditor.

Feel free to sent pull request with the patch for other text editors!

**Comment by get-web** [comment]
The language is switched, but the changes are not saved. Works, only the main language

**Pull request merged**
